[project]
name = "catfoodscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "black>=25.1.0",
    "furl>=2.1.4",
    "lxml>=6.0.0",
    "pytest>=8.4.1",
    "rnet>=2.3.9",
]
